### ISSUE TITLE
How to set the maximum running time?

### ISSUE THREAD

**Issue by Archer222arc** [sbjoshi/Open-WBO-Inc#2]
I'm trying to find if there is an option for setting maximum running time in the --help but failed. I'm wondering if there is a corresponding option?

**Comment by sbjoshi** [comment]
@Archer222arc there's no such option within the tool. Please use [runsolver](https://www.cril.univ-artois.fr/~roussel/runsolver/) to impose time or memory limits when you run the executable. You can use other utilities too which impose these limits and send a signal to the executable. The executable with catch the signal and gracefully terminate after printing statistics and partial solution (if found).

**Comment by Archer222arc** [comment]
Another issue I face is, when I was trying to running the solver with |tee command, it just stopped running and kept in the status. How can I get the output of solving as a file?
